### PR TITLE
Final Capstone Front End: Project setup

### PR DESCRIPTION
**Pull request by WilhelmK109**
- Install React with create-react-app ./
- Install all necessary packages such as react-router, redux, and Axios.
- Install liners and GitHub workflows.
- Remove all default files.
- Create README.md with a link to the back end.

### CODE REVIEW

**Review by AliShahSafdari — APPROVED** [review]
Hi @WilhelmK109, 
# STATUS: APPROVED! 🥇 💯 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed
- [ ] all views work correctly

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by SaneMyburg — APPROVED** [review]
## STATUS: APPROVED 🟢
Hi [@WilhelmK109](https://github.com/wilhelmk1090)
image

Your project is complete! There is nothing else to say other than... it's time to merge it :ship it:
Congratulations! 🎉

## (Highlights) Good Points: 👍
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- This milestone's requirements have been met with success. 🎉 🎉 🎉 ✔
- No linter errors 🤙👌✔
- Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**Comment by WilhelmK109** [comment]
@AliShahSafdari 👍

**Comment by WilhelmK109** [comment]
@SaneMyburg 👍

**Pull request merged**
